### ISSUE TITLE
Eliminate duplicate terminology

### ISSUE THREAD

**Issue by jyasskin** [w3c/webauthn#358]
I see several sets of equivalent terms in the spec. We should pick a canonical one from each set and eliminate the others (some of these also lack definitions, see also #462):

- [x] attestation key pair
  - [x] attestation key(s)
  - [x] public attestation keys
  - [x] key material

- [x] [Authentication Assertion](https://www.w3.org/TR/webauthn/#authentication-assertion)
  - [x] [Assertion](https://www.w3.org/TR/webauthn/#assertion)

- [ ] authenticator (these terms are the union of ones appearing in the spec and also used in various discussions):
  - [x] [platform authenticator](https://www.w3.org/TR/webauthn/#platform-authenticators)
  - [x] bound authenticator
  - [x] platform-provided authenticator
  - [x] built-in authenticator
  - [x] internal authenticator
  - [ ] others?
  - [x] [roaming authenticator](https://www.w3.org/TR/webauthn/#roaming-authenticators)
  - [x] cross-platform authenticator
  - [x] xplat authenticator   
  - [x] external authenticator
  - [ ] others?

- [x] [Client-side-resident Credential Private Key](https://w3c.github.io/webauthn/#client-side-resident-credential-private-key) (see also issue #936)
  - [x] replace [Client-side-resident Credential Private Key](https://w3c.github.io/webauthn/#client-side-resident-credential-private-key) with a "Client-side-resident [Credential Public Key Source](https://w3c.github.io/webauthn/#public-key-credential-source)" term with "resident credential" as the abbreviated form ?

- [x] create a "client-side-resident credential source" term rather than the "... private key" one?

- [x] also "client-side" is synonymous with "local", "server-side" with "remote" -- use both equivalently or coalesce to one or the other?

- [x] Collected Client Data i.e. [`CollectedClientData`](https://w3c.github.io/webauthn/#dictdef-collectedclientdata)
  - [x] [Client Data](https://www.w3.org/TR/webauthn/#sec-client-data)

- [x] [Conforming User Agent](https://www.w3.org/TR/webauthn/#conforming-user-agent)
  - [x] [Client](https://www.w3.org/TR/webauthn/#client)
  - [x] [WebAuthn Client](https://www.w3.org/TR/webauthn/#webauthn-client)

- [x] Credential ID
  - [x] credential identifier
  - [x] identifier of the credential

- [x] [Human-palatable](https://w3c.github.io/webauthn/#human-palatability) // should coverge on this
  - [x] human-friendly // old term
  - [x] human-readable // old term

- [x] Platform
  - [x] a platform
  - [x] underlying platform
  - [x] underlying OS platform
  - [x] [this|the] client platform
  - [x] client's platform
  - [x] [this|the] platform
  - [x] user agent and/or platform

- [x] public key
  - [x] credential public key (the term we are using as this time (see #79))
  - [x] public key of the credential

- [x] private key
  - [x] credential private key (the term we are using as this time (see #79))
  - [x] private key associated with the credential
  - [x] private key of the selected credential

- [x] [Relying Party](https://www.w3.org/TR/webauthn/#relying-party)
  - [x] RP  (perhaps continue to use this acronym and add it to the Relying Party dfn a la RP ID and decorate all occurances)

    so what we've actually done instead is not use the "RP" acronym except in a couple \<pre> blocks and instead use "[WebAuthn] Relying Party" everywhere via the text macros.

- [x] signature
  - [x] webauthn signature
  - [x] assertion signature
  - [x] authentication signature

- [x] user verification 
  - [x] obtains a biometric or other authorization gesture from the user (should be "verifies the user"?)

**Comment by equalsJeffH** [comment]
I removed..
>[User Verification](https://www.w3.org/TR/webauthn/#user-verification)
>* [Authorization Gesture](https://www.w3.org/TR/webauthn/#authorization-gesture)

from the original post because they were addressed in merged PR #365.

**Comment by equalsJeffH** [comment]
see also #79 

adding to the list in the original issue above:

public key
* credential public key (the term we are using as this time (see #79))
* public key of the credential

private key
* credential private key (the term we are using as this time (see #79))
* private key associated with the credential
* private key of the selected credential

**Comment by selfissued** [comment]
In some cases, it's fine to explicitly say that longer and shorter names are used equivalently in the specification, for instance, saying that "WebAuthn Relying Party", "Relying Party", and "RP" are equivalent as used in this specification.

It seems to me like all of these are editorial issues and not names used in APIs.  If this is the case, we should change it from being tagged as "Technical" to "Editorial".  Any API changes resulting from this issue need to be decided before the Implementer's Draft.

**Comment by AngeloKai** [comment]
Agreed on changing technical to editorial. I am not sure if this is necessary if our goal is getting the spec ready for implementation.

**Comment by equalsJeffH** [comment]
see also #462

**Comment by equalsJeffH** [comment]
adding to the original post (OP) aka original issue:

Credential ID
* credential identifier
* identifier of the credential

**Comment by equalsJeffH** [comment]
adding to the original post (OP): 

* key material

**Comment by equalsJeffH** [comment]
added to OP:

authenticator
* platform-provided authenticator
* platform authenticator

**Comment by equalsJeffH** [comment]
added to OP:

user verification 
* obtains a biometric or other authorization gesture from the user (should be "verifies the user"?)

**Comment by equalsJeffH** [comment]
added to OP:

signature
* webauthn signature

**Comment by AngeloKai** [comment]
As discussed on the call, the issue doesn't have to do with API name change but rather editorial changes. Taking out the renaming label.

**Comment by equalsJeffH** [comment]
added to OP: 

Client-side-resident Credential Private Key
 * resident credential

**Comment by equalsJeffH** [comment]
added to OP: 

Collected Client Data i.e. `CollectedClientData`
- Client Data

**Comment by equalsJeffH** [comment]
added to OP: 

[Human-palatable](https://w3c.github.io/webauthn/#human-palatability) // should coverge on this
* human-friendly // old term

**Comment by equalsJeffH** [comment]
added to OP:
authenticator (these terms are the union of ones appearing in the spec and also used in various discussions):
* [platform authenticator](https://www.w3.org/TR/webauthn/#platform-authenticators)
* platform-provided authenticator
* built-in authenticator
* internal authenticator
* others?
* [roaming authenticator](https://www.w3.org/TR/webauthn/#roaming-authenticators)
* cross-platform authenticator
* xplat authenticator
* external authenticator
* others?

**Comment by equalsJeffH** [comment]
added to OP:

[Client-side-resident Credential Private Key](https://w3c.github.io/webauthn/#client-side-resident-credential-private-key)
 * replace [Client-side-resident Credential Private Key](https://w3c.github.io/webauthn/#client-side-resident-credential-private-key) with a "Client-side-resident [Credential Public Key Source](https://w3c.github.io/webauthn/#public-key-credential-source)" term with "resident credential" as the abbreviated form ?

**Comment by equalsJeffH** [comment]
added to OP:

also "client-side" is synonymous with "local", "server-side" with "remote" -- use both equivalently or coalesce to one or the other?

**Comment by emlun** [comment]
Re: https://github.com/w3c/webauthn/issues/358#issuecomment-403977896 - I think "client-side" and "server-side" are probably better terms since they are absolute instead of relative.

**Comment by emlun** [comment]
Updated OP: added action item checkboxes.

**Comment by emlun** [comment]
Checked off:

- Client-side-resident stuff
- "client-side" is synonymous with "local", "server-side" with "remote"
- Conforming User Agent and sub-items
- Human-palatable and sub-items
- Platform and sub-items

**Comment by emlun** [comment]
Checked off:

>- [x] Credential ID
>    - [x] credential identifier
>    - [x] identifier of the credential
>- [ ] attestation key pair    
>    - [ ]  attestation key(s)
>    - [ ]  public attestation keys
>    - [x]  key material
>- [ ]  authenticator (these terms are the union of ones appearing in the spec and also used in various discussions):
>    - [ ]  [platform authenticator](https://www.w3.org/TR/webauthn/#platform-authenticators)
>    - [x]  bound authenticator
>    - [ ]  platform-provided authenticator
>    - [x]  built-in authenticator
>    - [ ]  internal authenticator
>    - [ ]  others?
>    - [ ]  [roaming authenticator](https://www.w3.org/TR/webauthn/#roaming-authenticators)
>    - [x]  cross-platform authenticator
>    - [x]  xplat authenticator
>    - [x]  external authenticator
>    - [ ]  others?
>- [x]  Collected Client Data i.e. [`CollectedClientData`](https://w3c.github.io/webauthn/#dictdef-collectedclientdata)
>    - [x]  [Client Data](https://www.w3.org/TR/webauthn/#sec-client-data)

**Comment by emlun** [comment]
Fixed by #1334:

>- [x] [Authentication Assertion](https://www.w3.org/TR/webauthn/#authentication-assertion)      
>    - [x] [Assertion](https://www.w3.org/TR/webauthn/#assertion)
>- [x] attestation key pair    
>    - [x]  attestation key(s)
>    - [x]  public attestation keys
>- [x]  authenticator (these terms are the union of ones appearing in the spec and also used in various discussions):
>    - [x]  [platform authenticator](https://www.w3.org/TR/webauthn/#platform-authenticators)
>    - [x]  platform-provided authenticator
>    - [x]  internal authenticator
>    - [ ]  others?
>    - [x]  [roaming authenticator](https://www.w3.org/TR/webauthn/#roaming-authenticators)
>    - [ ]  others?
>- [x]  public key 
>    - [x]  credential public key (the term we are using as this time (see #79))
>    - [x]  public key of the credential
>- [x]  private key
>    - [x]  credential private key (the term we are using as this time (see #79))
>    - [x]  private key associated with the credential
>    - [x]  private key of the selected credential
>- [x]  signature
>    - [x]  webauthn signature
>    - [x]  assertion signature
>    - [x]  authentication signature
>- [x]  user verification
>    - [x]  obtains a biometric or other authorization gesture from the user (should be "verifies the user"?)



***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/pull/1334.html" title="Last updated on Oct 22, 2019, 2:35 PM UTC (ddb93e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/1334/a55edbf...ddb93e8.html" title="Last updated on Oct 22, 2019, 2:35 PM UTC (ddb93e8)">Diff</a>

**Comment by emlun** [comment]
All that remains here now is the "others?" items under "authenticator", so I think we can argue this is done. :smile:

**Comment by emlun** [comment]
Oh wait, that's not merged yet... But when we do merge it. :sweat_smile:

**Comment by equalsJeffH** [comment]
this is done, we can open a new one if we find new duplicate terminology...
